---
version: 2.1

orbs:
  do: twdps/pipeline-events@dev:<<pipeline.git.revision>>
  op: twdps/onepassword@2.0.2

globals:
  - &context orb-publishing

commands:

  echo-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo msg
          command: echo "<< parameters.msg >>"

jobs:

  test pipeline events:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - op/packages:
          op-version: 2.25.0-1
      - do/packages:
          gren-version: 0.17.3
          datadog-version: 0.47.0
      - op/env
      - do/set-docker-credentials
      - do/bash-functions

workflows:

  integration tests:
    jobs:
      - test pipeline events:
          context: *context
      - do/slack:
          context: *context
          channel: lab-events
          message: orb-pipeline-events dev build test of slack message job with button
          include-link: true
          before-message:
            - op/env
            - echo-message:
                msg: "before slack message"
          after-message:
            - echo-message:
                msg: "after slack message"